# NodeJS Version 20.11.1
FROM node:20.11.1-buster-slim

# Copy Dir
COPY . ./solace

# Work to Dir
WORKDIR /solace

# Install Node Package
RUN npm install

# Set Env
ENV NODE_ENV production

# Cmd script
CMD ["npm", "run", "dev"]
